services:
  app:
    build:
      context: .
    env_file: 
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/home/app-user/app
      - /home/app-user/app/.next # Exclude .next folder from the host to avoid conflicts
    command: >
      sh -c "
      until pg_isready -h localhost -p 5432; do
      echo 'Waiting for PostgreSQL...';
      sleep 3;
      done;
      npx prisma migrate deploy &&
      npm run dev
      "
